/* Durable, local history. Read-only reports are explicitly refreshed, never polled. */
(function () {
  'use strict';
  const $ = id => document.getElementById(id);
  const n = v => Number.isFinite(v) ? v : 0;
  const count = v => n(v).toLocaleString();
  const money = v => v == null ? '—' : new Intl.NumberFormat(undefined,{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:v<1?5:2}).format(v);
  const ms = v => v == null ? '—' : v < 1000 ? `${Math.round(v)} ms` : `${(v/1000).toFixed(v<10000?2:1)} s`;
  const pct = (a,b) => b ? `${(100*n(a)/b).toFixed(1)}%` : '—';
  const when = v => v == null ? '—' : new Date(v).toLocaleString();
  const localInput = v => {const d=new Date(v);return new Date(v-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
  function delta(a,b) {return b ? `${a>=b?'+':''}${(100*(a-b)/b).toFixed(1)}% vs previous period` : 'No previous-period baseline';}
  if(typeof module!=='undefined'&&module.exports)module.exports={delta,pct,ms,money};
  if(typeof document==='undefined')return;
  const state={loaded:false,busy:false,params:null,report:null,history:null,cursors:[null],page:0,sort:'requests',descending:true};
  const node=(tag,text,cls)=>{const el=document.createElement(tag);if(text!=null)el.textContent=text;if(cls)el.className=cls;return el;};
  const link=(text,fn)=>{const el=node('button',text,'report-link');el.type='button';el.onclick=fn;return el;};
  function table(headers,rows){const t=node('table'),head=node('tr');for(const h of headers){const th=node('th');if(h instanceof Node)th.append(h);else th.textContent=h;head.append(th);}const thead=node('thead');thead.append(head);t.append(thead);const body=node('tbody');for(const row of rows){const tr=node('tr');for(const value of row){const td=node('td');if(value instanceof Node)td.append(value);else td.textContent=value??'—';tr.append(td);}body.append(tr);}t.append(body);return t;}
  const put=(id,child)=>$(id).replaceChildren(child);
  const outcome=e=>node('span',e.state||'unknown',`outcome ${['succeeded','failed','cancelled','interrupted'].includes(e.state)?e.state:''}`);
  const fields=['model','project','state','path','transport','search'];
  function dates(){const period=$('report-period').value,now=Date.now();if(period==='custom')return;$('report-start').value=localInput(period==='all'?0:now-Number(period)*3600000);$('report-end').value=localInput(now+60000);}
  function parameters(){dates();const period=$('report-period').value,end=period==='custom'?new Date($('report-end').value).getTime():Date.now()+1,start=period==='custom'?new Date($('report-start').value).getTime():period==='all'?(state.report?.storage.earliest_ms||0):end-Number(period)*3600000;if(!Number.isFinite(start)||!Number.isFinite(end)||start>=end)throw new Error('Choose a valid start and end time.');const p=new URLSearchParams({start:String(start),end:String(end),group:$('report-group').value,model_field:$('report-model-field').value,limit:'100',include_clients:String($('report-clients').checked)});for(const name of fields){const v=$(`report-${name}`).value.trim();if(v)p.set(name==='search'?'q':name,v);}return p;}

  async function api(path,params){const r=await fetch(`/logs/api/${path}${params?'?'+params:''}`,{cache:'no-store',signal:AbortSignal.timeout(15000)});if(!r.ok){let message;try{message=(await r.json()).error;}catch{}throw new Error(r.status===401?'Access expired. Sign in again at /logs.':message||`Report unavailable (HTTP ${r.status}).`);}return r;}
  function error(err){$('report-error').hidden=false;$('report-error').textContent=err.message;$('report-filter-note').textContent=state.loaded?'Previous results remain below; refresh failed.':'Unable to load report.';}
  function busy(value){state.busy=value;for(const el of $('report-form').elements)el.disabled=value;for(const id of ['report-csv','report-jsonl','report-next','report-prev'])$(id).disabled=value;$('report-apply').textContent=value?'Reading history…':'Apply & refresh';if(!value&&state.history)pages();}
  function health(h){const el=$('report-health');el.classList.toggle('degraded',!h.enabled||h.status!=='healthy');if(!h.enabled){el.textContent='Persistent logging is disabled in this running process. Historical reports are unavailable.';return;}el.textContent=`Logging ${h.status} · ${count(h.pending_events)} events pending · ${count(h.dropped_events)} dropped events · ${count(h.write_errors)} write failures · last commit ${h.last_commit_ms?when(h.last_commit_ms):'waiting'}${h.pending_events?` · lag ${ms(h.lag_ms)}`:''}${h.last_error?` · ${h.last_error}`:''}`;if(h.dropped_events)el.append(node('div','History has gaps. Totals and timelines may omit events that could not be queued.'));}
  async function load(){if(state.busy)return;let params;try{params=parameters();}catch(e){error(e);return;}busy(true);$('report-error').hidden=true;$('report-filter-note').textContent='Reading a consistent database snapshot…';try{const [report,history]=await Promise.all([api('reports',params).then(r=>r.json()),api('history',params).then(r=>r.json())]);state.params=params;state.report=report;state.history=history;state.page=0;state.cursors=[null];state.loaded=true;health(report.logging);render();$('report-content').hidden=false;$('report-filter-note').textContent='Applied. Reports refresh on demand.';}catch(e){error(e);}finally{busy(false);}}
  function card(title,value,note,comparison){const el=node('div',null,'card report-card');el.append(node('span',title,'sub'),node('strong',value),node('small',note),node('small',comparison));return el;}
  function render(){const r=state.report,s=r.summary,p=r.previous,finished=n(s.succeeded)+n(s.failed)+n(s.cancelled)+n(s.interrupted);$('report-range').textContent=`${when(r.start)} → ${when(r.end)} · local history`;$('report-query').textContent=`${r.query_ms} ms query · snapshot ${when(r.snapshot_ms)}`;
    $('report-cards').replaceChildren(card('Requests',count(s.requests),`${count(s.active)} still active`,delta(n(s.requests),n(p.requests))),card('Completed successfully',pct(s.succeeded,finished),`${count(s.succeeded)} of ${count(finished)} ended`,`${count(s.failed)} failed · ${count(s.cancelled)} cancelled`),card('Total lifetime · p95',ms(s.total_duration_ms.p95),`Median ${ms(s.total_duration_ms.p50)}`,`p99 ${ms(s.total_duration_ms.p99)}`),card('First output · p50',ms(s.first_output_ms.p50),`p95 ${ms(s.first_output_ms.p95)}`,'Observed output event, including queue/recovery'),card('Reported tokens',s.usage_reported?count(n(s.input_tokens)+n(s.output_tokens)):'—',`${pct(s.usage_reported,s.requests)} request usage coverage`,`${count(s.cached_input_tokens)} cached input`),card('Estimated spend · USD',money(s.estimated_cost_usd),`${count(s.priced_requests)} / ${count(s.requests)} requests priced`,delta(n(s.estimated_cost_usd),n(p.estimated_cost_usd))));
    const metrics=[['Retries',count(s.retries)],['Requests retried',pct(s.retried_requests,s.requests)],['Cache read share',pct(s.cached_input_tokens,s.input_tokens)],['Reasoning tokens',count(s.reasoning_tokens)],['Interrupted',count(s.interrupted)],['Response data',`${(n(s.response_bytes)/1048576).toFixed(2)} MiB`]];$('report-secondary').replaceChildren(...metrics.map(([label,value])=>{const el=node('span',label+' ');el.append(node('b',value));return el;}));
    $('report-charts').replaceChildren(chart('Traffic & outcomes','requests',count,true),chart('List-price spend','estimated_cost_usd',money),chart('Mean completed lifetime','avg_duration_ms',ms));
    put('report-latencies',table(['Measurement','p50','p95','p99'],[['Headers / first send','duration_ms'],['First response byte','first_byte_ms'],['First output event','first_output_ms'],['Total ended lifetime','total_duration_ms']].map(([label,key])=>[label,...['p50','p95','p99'].map(p=>ms(s[key][p]))])));
    put('report-errors',r.errors.length?table(['Reason','Requests'],r.errors.map(e=>[e.error_code,count(e.requests)])):node('p','No failures in this selection.','empty'));
    groups();history();outliers('report-slowest',r.slowest,e=>ms(e.total_duration_ms));outliers('report-expensive',r.most_expensive,e=>money(e.estimated_cost_usd));
    $('report-storage').textContent=`Database: ${count(r.storage.retained_requests)} retained requests · earliest ${when(r.storage.earliest_ms)} · newest ${when(r.storage.latest_ms)}. All retained history; collection begins when persistent logging is enabled. Previously discarded live history cannot be reconstructed.`;
  }
  function chart(title,key,format,stacked=false){const r=state.report,wrap=node('div',null,'card'),svg=document.createElementNS('http://www.w3.org/2000/svg','svg'),hint=node('p','Hover or focus a bar for exact values.','chart-hint');svg.setAttribute('viewBox','0 0 520 170');svg.setAttribute('role','img');svg.setAttribute('aria-label',title);const sv=(tag,attrs,text)=>{const el=document.createElementNS(svg.namespaceURI,tag);for(const [k,v]of Object.entries(attrs))el.setAttribute(k,v);if(text!=null)el.textContent=text;svg.append(el);return el;};const bins=Array.from({length:60},(_,i)=>r.series.find(b=>b.bucket===i)||{}),max=Math.max(0,...bins.map(b=>n(b[key])))||1;for(let i=0;i<3;i++){const y=18+i*57;sv('line',{x1:48,x2:515,y1:y,y2:y,stroke:'var(--grid)'});sv('text',{x:43,y:y+4,'text-anchor':'end'},format(max*(1-i/2)));}bins.forEach((b,i)=>{const x=50+i*7.7,h=n(b[key])/max*114;const bar=sv('rect',{x,y:132-h,width:5.5,height:Math.max(h,.4),fill:stacked?'var(--accent)':'var(--accent)',opacity:b[key]==null?.18:1,tabindex:0,role:'graphics-symbol','aria-label':`${when(r.start+i*r.bucket_ms)}: ${format(b[key])}`});const detail=`${when(r.start+i*r.bucket_ms)} · ${format(b[key])}${stacked?` · ${count(b.succeeded)} succeeded / ${count(b.failed)} failed / ${count(b.active)} active`:''}`;bar.addEventListener('mouseenter',()=>hint.textContent=detail);bar.addEventListener('focus',()=>hint.textContent=detail);if(stacked&&b.requests){const failed=n(b.failed)+n(b.cancelled)+n(b.interrupted);sv('rect',{x,y:132-h,width:5.5,height:failed/max*114,fill:'var(--bad)','pointer-events':'none'});}});sv('text',{x:50,y:155},new Date(r.start).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}));sv('text',{x:515,y:155,'text-anchor':'end'},new Date(r.end).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}));wrap.append(node('h2',title),svg,hint);return wrap;}
  function groups(){const r=state.report,headers=[['Group','name'],['Requests','requests'],['Succeeded','succeeded'],['Failed','failed'],['Input tokens','input_tokens'],['Output tokens','output_tokens'],['Cache read','cached_input_tokens'],['Est. spend','estimated_cost_usd'],['Priced','priced_requests'],['Mean lifetime','avg_duration_ms'],['Retries','retries']];const sorted=[...r.groups].sort((a,b)=>{const d=typeof a[state.sort]==='string'?a[state.sort].localeCompare(b[state.sort]):n(a[state.sort])-n(b[state.sort]);return state.descending?-d:d;});$('report-group-title').textContent=`Breakdown by ${r.group.replaceAll('_',' ')}`;$('report-group-note').textContent=r.groups_truncated?'Top 100 groups by request count · refine filters to see others':'Click a column to sort or a group to filter';put('report-groups',sorted.length?table(headers.map(([label,key])=>link(label+(state.sort===key?(state.descending?' ↓':' ↑'):''),()=>{state.descending=state.sort===key?!state.descending:true;state.sort=key;groups();})),sorted.map(g=>[link(g.name,()=>{if(g.name==='(unknown)')return;if(['requested_model','routed_model'].includes(r.group)){$('report-model-field').value=r.group;$('report-model').value=g.name;}else $(`report-${r.group}`).value=g.name;load();}),count(g.requests),count(g.succeeded),count(g.failed),g.input_tokens==null?'—':count(g.input_tokens),g.output_tokens==null?'—':count(g.output_tokens),g.cached_input_tokens==null?'—':count(g.cached_input_tokens),money(g.estimated_cost_usd),`${count(g.priced_requests)}/${count(g.requests)}`,ms(g.avg_duration_ms),count(g.retries)])):node('p','No requests match these filters.','empty'));}
  function history(){const h=state.history;$('report-history-note').textContent=`${count(h.total)} matches · newest first · select a request for its timeline`;put('report-history',h.entries.length?table(['Started','Request / model','Outcome','HTTP','Retries','Tokens in / out','Total lifetime','Est. spend'],h.entries.map(e=>{const request=node('div');request.append(link(`${e.method} ${e.path}`,()=>detail(e.request_id)),node('div',`${e.requested_model||'—'} → ${e.routed_model||'—'}`,'muted'));return [when(e.timestamp_ms),request,outcome(e),e.status??'—',count(e.retries),`${e.input_tokens==null?'—':count(e.input_tokens)} / ${e.output_tokens==null?'—':count(e.output_tokens)}`,ms(e.total_duration_ms),money(e.estimated_cost_usd)];})):node('p','No stored requests match these filters.','empty'));pages();}
  function pages(){$('report-prev').disabled=state.busy||state.page===0;$('report-next').disabled=state.busy||!state.history.next_cursor;$('report-page').textContent=`Page ${state.page+1} · ${state.history.entries.length} requests`;}
  async function page(direction){if(state.busy)return;const target=state.page+direction;if(target<0)return;if(direction>0)state.cursors[target]=state.history.next_cursor;const params=new URLSearchParams(state.params);if(state.cursors[target])params.set('cursor',state.cursors[target]);busy(true);$('report-error').hidden=true;try{const data=await api('history',params).then(r=>r.json());state.history=data;state.page=target;history();}catch(e){error(e);}finally{busy(false);}}
  function outliers(id,data,value){put(id,data.length?table(['Request', 'Value'],data.map(e=>[link(e.requested_model||e.path,()=>detail(e.request_id)),value(e)])):node('p','No measurements available.','empty'));}
  let detailSequence=0;
  async function detail(id){const sequence=++detailSequence;$('request-title').textContent='Request detail';put('request-detail',node('p','Loading lifecycle…','modal-summary'));if(!$('request-modal').open)$('request-modal').showModal();try{const d=await api(`requests/${encodeURIComponent(id)}`).then(r=>r.json());if(sequence!==detailSequence)return;const e=d.request,dl=node('dl',null,'request-fields');const values=[['Request ID',e.request_id],['Session',e.session_id],['Started',when(e.timestamp_ms)],['Ended',when(e.ended_ms)],['Outcome',e.state],['Source / error',`${e.outcome_source||'—'} / ${e.error_code||'—'}`],['Request',`${e.method} ${e.path}`],['Transport',e.transport],['Project',e.project],['Requested → destination',`${e.requested_model||'—'} → ${e.routed_model||'—'}`],['Incoming reasoning effort',e.route_rule?(e.requested_reasoning||'Not supplied'):'Not recorded'],['Sent reasoning effort',e.route_rule?(e.routed_reasoning||'Not supplied'):'Not recorded'],['Routing rule',e.route_rule||'Not recorded'],['Status',e.status],['Security guidance',e.security_guidance?'Skip blocked work reminder applied':'Not recorded'],['Attempts / retries',`${e.attempts} / ${e.retries}`],['Headers / first send',ms(e.duration_ms)],['First byte / output',`${ms(e.first_byte_ms)} / ${ms(e.first_output_ms)}`],['Total lifetime',ms(e.total_duration_ms)],['Input / output',`${e.input_tokens??'—'} / ${e.output_tokens??'—'}`],['Cache read / write',`${e.cached_input_tokens??'—'} / ${e.cache_write_tokens??'—'}`],['Reasoning tokens',e.reasoning_tokens],['List-price estimate',money(e.estimated_cost_usd)],['Price model / version',`${e.price_model||'—'} / ${e.price_version||'—'}`],['Bytes in / out',`${count(e.request_bytes)} / ${count(e.response_bytes)}`],['Upstream request ID',e.upstream_request_id],['Response ID',e.response_id]];for(const [label,value]of values){const item=node('div');item.append(node('dt',label),node('dd',value??'—'));dl.append(item);}const timeline=table(['Since arrival','Event','Details'],d.events.map(ev=>[ms(Math.max(0,ev.timestamp_ms-e.timestamp_ms)),ev.kind,node('pre',JSON.stringify(ev.details,null,2))]));$('request-detail').replaceChildren(dl,node('h3','Lifecycle timeline'),timeline,node('p',d.events_truncated?'Showing the first 2,000 events. Additional events are retained in SQLite.':'Metadata only: no prompts, payloads, credentials or raw error messages.','sub'));}catch(err){if(sequence===detailSequence)put('request-detail',node('p',err.message,'notice'));}}
  async function download(format){if(state.busy||!state.params)return;const params=new URLSearchParams(state.params);params.set('format',format);busy(true);$('report-error').hidden=true;try{const response=await api('export',params),blob=await response.blob(),url=URL.createObjectURL(blob),a=node('a');a.href=url;a.download=`hey-proxy-requests.${format}`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);$('report-filter-note').textContent=`Complete ${format.toUpperCase()} export downloaded for the applied filters.`;}catch(e){error(e);}finally{busy(false);}}
  $('report-form').onsubmit=e=>{e.preventDefault();load();};$('report-form').oninput=()=>{$('report-filter-note').textContent='Filters changed. Apply to update the results.';};$('report-period').onchange=()=>{dates();if($('report-period').value!=='custom')load();};for(const id of ['report-start','report-end'])$(id).onchange=()=>{$('report-period').value='custom';};$('report-reset').onclick=()=>{for(const field of fields)$(`report-${field}`).value='';$('report-clients').checked=false;$('report-group').value='requested_model';$('report-model-field').value='requested_model';$('report-period').value='24';dates();load();};$('report-prev').onclick=()=>page(-1);$('report-next').onclick=()=>page(1);$('report-csv').onclick=()=>download('csv');$('report-jsonl').onclick=()=>download('jsonl');$('request-close').onclick=()=>$('request-modal').close();$('request-modal').addEventListener('close',()=>detailSequence++);
  async function checkHealth(){if(location.hash!=='#reports')return;try{health(await api('health').then(r=>r.json()));}catch(e){$('report-health').textContent=e.message;$('report-health').classList.add('degraded');}}
  function route(){if(location.hash==='#reports'){checkHealth();if(!state.loaded&&!state.busy)load();}}
  dates();addEventListener('hashchange',route);route();setInterval(checkHealth,5000);
})();
